# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 604)
        MainWindow.setStyleSheet("QScrollBar:horizontal{\n"
"    height:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"border-radius:4px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"    background:rgba(125,125,125,50%);\n"
"border-radius:4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background:rgba(125,125,125,100%);\n"
"    min-width:0;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    width:0px;\n"
"    background:rgba(125,125,125,50%);\n"
"    border-radius:4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    width:0px;\n"
"    background:rgba(125,125,125,100%);\n"
"    border-radius:4px;\n"
"    min-width:20;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HeadFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.HeadFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(44, 62, 80);\n"
"    border: none;\n"
"    padding: 2px;\n"
"}")
        self.HeadFrame.setObjectName("HeadFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.HeadFrame)
        self.horizontalLayout.setContentsMargins(24, 0, 0, 0)
        self.horizontalLayout.setSpacing(24)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_head_logo = QtWidgets.QWidget(parent=self.HeadFrame)
        self.widget_head_logo.setMinimumSize(QtCore.QSize(36, 36))
        self.widget_head_logo.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setFamily("MS Reference Specialty")
        self.widget_head_logo.setFont(font)
        self.widget_head_logo.setStyleSheet("image: url(\"resources/img/机器人.svg\");")
        self.widget_head_logo.setObjectName("widget_head_logo")
        self.horizontalLayout.addWidget(self.widget_head_logo)
        self.Head_Titlelabel = QtWidgets.QLabel(parent=self.HeadFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.Head_Titlelabel.setFont(font)
        self.Head_Titlelabel.setStyleSheet("QLabel { \n"
"    color: rgb(255, 255, 255); \n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\'; \n"
"}")
        self.Head_Titlelabel.setObjectName("Head_Titlelabel")
        self.horizontalLayout.addWidget(self.Head_Titlelabel)
        self.listWidget_Head = QtWidgets.QListWidget(parent=self.HeadFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Head.sizePolicy().hasHeightForWidth())
        self.listWidget_Head.setSizePolicy(sizePolicy)
        self.listWidget_Head.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_Head.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.listWidget_Head.setFont(font)
        self.listWidget_Head.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.listWidget_Head.setStyleSheet("QListView {\n"
"    background: transparent;\n"
"    color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    outline: none;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QListView::item {\n"
"    background: transparent;\n"
"    padding: 12px 20px;\n"
"    margin: 4px 8px;\n"
"    border-radius: 6px;\n"
"    border: 1px solid transparent;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background: rgba(255, 255, 255, 0.05);\n"
"    color: #7AD8FF;\n"
"    border-color: rgba(255, 255, 255, 0.15);\n"
"    transform: translateX(4px);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background: rgba(255, 255, 255, 0.08);\n"
"    color: #7AD8FF;\n"
"    font-weight: 500;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"QListView::item:!enabled {\n"
"    color: #888888;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgba(30, 30, 30, 0.8);\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(255, 255, 255, 0.3);\n"
"    border-radius: 4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"}")
        self.listWidget_Head.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_Head.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_Head.setFlow(QtWidgets.QListView.Flow.LeftToRight)
        self.listWidget_Head.setObjectName("listWidget_Head")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Head.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Head.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Head.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget_Head)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.HeadFrame)
        self.MainFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.MainFrame.setMinimumSize(QtCore.QSize(805, 538))
        self.MainFrame.setStyleSheet("QFrame{\n"
"    background-color: rgba(44, 62, 80,0.8);\n"
"}")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.MainFrame)
        self.horizontalLayout_7.setContentsMargins(32, 20, 32, 20)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.MainFrame)
        self.stackedWidget.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"border-radius:14px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_h1 = QtWidgets.QFrame(parent=self.page)
        self.frame_h1.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.frame_h1.setObjectName("frame_h1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_h1)
        self.horizontalLayout_3.setContentsMargins(0, 12, 0, 12)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_Title = QtWidgets.QLabel(parent=self.frame_h1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.horizontalLayout_3.addWidget(self.label_Title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_h1)
        self.verticalLayout_line = QtWidgets.QVBoxLayout()
        self.verticalLayout_line.setSpacing(0)
        self.verticalLayout_line.setObjectName("verticalLayout_line")
        self.line_welcome = QtWidgets.QFrame(parent=self.page)
        self.line_welcome.setMinimumSize(QtCore.QSize(0, 1))
        self.line_welcome.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_welcome.setStyleSheet("background:rgba(168, 168, 168, 156);")
        self.line_welcome.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_welcome.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_welcome.setObjectName("line_welcome")
        self.verticalLayout_line.addWidget(self.line_welcome)
        self.verticalLayout_2.addLayout(self.verticalLayout_line)
        self.frame_4 = QtWidgets.QFrame(parent=self.page)
        self.frame_4.setStyleSheet(".QFrame{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-radius:20px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_welcome = QtWidgets.QHBoxLayout()
        self.horizontalLayout_welcome.setContentsMargins(-1, 28, -1, 28)
        self.horizontalLayout_welcome.setObjectName("horizontalLayout_welcome")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_welcome.addItem(spacerItem2)
        self.label_welcome = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_welcome.setFont(font)
        self.label_welcome.setStyleSheet("QLabel { \n"
"    color: rgb(44,62,80);\n"
"    background:rgba(0, 0, 0, 0);\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\'; \n"
"}")
        self.label_welcome.setObjectName("label_welcome")
        self.horizontalLayout_welcome.addWidget(self.label_welcome)
        self.label_Nickname = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_Nickname.setFont(font)
        self.label_Nickname.setStyleSheet("QLabel { \n"
"    color: rgb(44,62,80);\n"
"    background:rgba(0, 0, 0, 0);\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\'; \n"
"}")
        self.label_Nickname.setObjectName("label_Nickname")
        self.horizontalLayout_welcome.addWidget(self.label_Nickname)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_welcome.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_welcome)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 22, -1, 22)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_start = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_start.setMinimumSize(QtCore.QSize(200, 91))
        self.pushButton_start.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                stop:0 hsl(141, 40%, 55%),\n"
"                stop:0.5 hsl(141, 40%, 48%),\n"
"                stop:1 hsl(141, 40%, 42%));\n"
"    border-radius: 12px;\n"
"    border: 2px solid rgba(255,255,255,0.12);\n"
"    padding: 12px 28px;\n"
"    min-width: 140px;\n"
"    color: #f8f9fa;\n"
"    letter-spacing: 0.8px;\n"
"    text-transform: uppercase;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1),\n"
"                transform 0.15s ease-out;\n"
"    box-shadow: \n"
"        0 4px 18px -4px rgba(0,0,0,0.2),\n"
"        0 6px 12px -6px rgba(0,0,0,0.1),\n"
"        inset 0 -2px 4px rgba(0,0,0,0.08),\n"
"        inset 0 2px 4px rgba(255,255,255,0.2);\n"
"    text-shadow: 0 1px 2px rgba(0,0,0,0.15);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                stop:0 hsl(141, 45%, 60%),\n"
"                stop:0.5 hsl(141, 45%, 53%),\n"
"                stop:1 hsl(141, 45%, 47%));\n"
"    border-color: rgba(255,255,255,0.2);\n"
"    box-shadow: \n"
"        0 8px 32px -4px rgba(0,0,0,0.3),\n"
"        0 12px 24px -8px rgba(60, 140, 100, 0.25),\n"
"        inset 0 -2px 4px rgba(0,0,0,0.1),\n"
"        inset 0 2px 4px rgba(255,255,255,0.3);\n"
"    transform: translateY(-3px) scale(1.02);\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                stop:0 hsl(141, 35%, 45%),\n"
"                stop:0.5 hsl(141, 35%, 40%),\n"
"                stop:1 hsl(141, 35%, 35%));\n"
"    box-shadow: \n"
"        0 2px 8px rgba(0,0,0,0.15),\n"
"        inset 0 3px 6px rgba(0,0,0,0.12);\n"
"    transform: translateY(2px) scale(0.98);\n"
"    transition-duration: 0.1s;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                stop:0 hsl(0, 0%, 75%),\n"
"                stop:1 hsl(0, 0%, 65%));\n"
"    color: rgba(255,255,255,0.7);\n"
"    border-color: rgba(255,255,255,0.1);\n"
"    text-shadow: none;\n"
"    box-shadow: 0 3px 6px rgba(0,0,0,0.1);\n"
"    opacity: 0.9;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: 2px solid rgba(120, 220, 150, 0.4);\n"
"    outline-offset: 4px;\n"
"    box-shadow: \n"
"        0 0 0 4px rgba(120, 220, 150, 0.2),\n"
"        0 8px 32px -4px rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QPushButton[icon] {\n"
"    padding-left: 20px;\n"
"    padding-right: 32px;\n"
"    background-position: right 20px center;\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    margin-right: 12px;\n"
"    transition: transform 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover::icon {\n"
"    transform: translateX(2px);\n"
"}\n"
"\n"
"QPushButton:pressed::icon {\n"
"    transform: translateX(4px);\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.verticalFrame_Onlinestatus_2 = QtWidgets.QFrame(parent=self.frame_4)
        self.verticalFrame_Onlinestatus_2.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalFrame_Onlinestatus_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalFrame_Onlinestatus_2.setStyleSheet("QFrame {\n"
"    background-color: #2C3E50;\n"
"    border-radius: 16px;\n"
"    padding: 8px;\n"
"    border: 1px solid transparent;\n"
"    transition: all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);\n"
"    background-image: linear-gradient(145deg, rgba(44, 62, 80, 0.95), rgba(38, 54, 70, 0.98));\n"
"    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08), inset 0 1px 2px rgba(255, 255, 255, 0.08);\n"
"}\n"
"\n"
"QFrame:pressed {\n"
"    background-color: rgba(140, 190, 240, 0.9);\n"
"    border-color: rgba(220, 235, 255, 0.9);\n"
"    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1), inset 0 1px 2px rgba(0, 0, 0, 0.05);\n"
"    transform: translateY(2px) scale(0.995);\n"
"    transition-duration: 0.2s;\n"
"}\n"
"\n"
"QFrame:focus {\n"
"    outline: 2px solid rgba(160, 200, 255, 0.4);\n"
"    outline-offset: 2px;\n"
"}\n"
"\n"
"QFrame:disabled {\n"
"    opacity: 0.6;\n"
"    filter: grayscale(0.4);\n"
"    transform: none;\n"
"}")
        self.verticalFrame_Onlinestatus_2.setObjectName("verticalFrame_Onlinestatus_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalFrame_Onlinestatus_2)
        self.verticalLayout_17.setContentsMargins(0, 9, 0, 12)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_time = QtWidgets.QLabel(parent=self.verticalFrame_Onlinestatus_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("QLabel { \n"
"    color: rgb(255, 255, 255);\n"
"    background:rgba(0, 0, 0, 0);\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\'; \n"
"    border: none;\n"
"}")
        self.label_time.setObjectName("label_time")
        self.verticalLayout_17.addWidget(self.label_time)
        self.horizontalLayout_2.addWidget(self.verticalFrame_Onlinestatus_2)
        self.verticalFrame_Onlinestatus = QtWidgets.QFrame(parent=self.frame_4)
        self.verticalFrame_Onlinestatus.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalFrame_Onlinestatus.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalFrame_Onlinestatus.setStyleSheet("QFrame {\n"
"    color: #2C3E50;\n"
"    background-color: rgba(199, 228, 255, 0.9);\n"
"    border-radius: 16px;\n"
"    padding: 8px;\n"
"    border: 1px solid transparent;\n"
"    transition: all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);\n"
"    background-image: linear-gradient(145deg, rgba(199, 228, 255, 0.95), rgba(185, 215, 240, 0.98));\n"
"    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08), inset 0 1px 2px rgba(255, 255, 255, 0.1);\n"
"}\n"
"\n"
"QFrame:pressed {\n"
"    background-color: rgba(140, 190, 240, 0.9);\n"
"    border-color: rgba(220, 235, 255, 0.9);\n"
"    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1), inset 0 1px 2px rgba(0, 0, 0, 0.05);\n"
"    transform: translateY(2px) scale(0.98);\n"
"    transition-duration: 0.2s;\n"
"}\n"
"\n"
"QFrame:focus {\n"
"    outline: 2px solid rgba(160, 200, 255, 0.4);\n"
"    outline-offset: 2px;\n"
"}\n"
"\n"
"QFrame:disabled {\n"
"    opacity: 0.7;\n"
"    filter: grayscale(0.3);\n"
"    transform: none;\n"
"}")
        self.verticalFrame_Onlinestatus.setObjectName("verticalFrame_Onlinestatus")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame_Onlinestatus)
        self.verticalLayout_10.setContentsMargins(0, 9, 0, 12)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_Online_Status = QtWidgets.QLabel(parent=self.verticalFrame_Onlinestatus)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_Online_Status.setFont(font)
        self.label_Online_Status.setStyleSheet("QLabel { \n"
"    color: rgb(63, 158, 255);\n"
"    background:rgba(0, 0, 0, 0);\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\'; \n"
"    border: none;\n"
"}")
        self.label_Online_Status.setObjectName("label_Online_Status")
        self.verticalLayout_10.addWidget(self.label_Online_Status)
        self.horizontalLayout_2.addWidget(self.verticalFrame_Onlinestatus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit_log = QtWidgets.QTextEdit(parent=self.frame_4)
        self.textEdit_log.setStyleSheet("QTextEdit {\n"
"    background-color: #f8f9fa;\n"
"    border: 1px solid rgba(44,62,80,0.2);\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    font-size: 18px;\n"
"    color: rgba(44,62,80,0.9);\n"
"    selection-background-color: rgba(44,62,80,0.3);\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    border-color: rgba(44,62,80,0.4);\n"
"    box-shadow: 0 3px 12px rgba(44,62,80,0.08);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 8px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(44,62,80,0.3);\n"
"    border-radius: 4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(44,62,80,0.5);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}")
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        self.horizontalLayout_4.addWidget(self.textEdit_log)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.page_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -127, 713, 658))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalFrame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_5.setContentsMargins(9, 9, 9, 12)
        self.horizontalLayout_5.setSpacing(9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalFrame_2 = QtWidgets.QFrame(parent=self.horizontalFrame)
        self.verticalFrame_2.setStyleSheet("QFrame {\n"
"    background-color: rgba(248, 249, 250, 0.8);\n"
"    border: 1px solid rgba(44, 62, 80, 0.12);\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 8px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    border-color: rgba(44, 62, 80, 0.2);\n"
"    box-shadow: 0 4px 16px rgba(44, 62, 80, 0.1);\n"
"    transform: translateY(-1px);\n"
"}\n"
"\n"
"QFrame:focus {\n"
"    border: 1px solid rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.1),\n"
"                0 6px 20px rgba(44, 62, 80, 0.15);\n"
"}\n"
"\n"
"QFrame::drop-shadow {\n"
"    background-color: rgba(44, 62, 80, 0.06);\n"
"    border-radius: 10px;\n"
"}")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_listen_friends_list = QtWidgets.QLabel(parent=self.verticalFrame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_listen_friends_list.setFont(font)
        self.label_listen_friends_list.setStyleSheet("QLabel { \n"
"    color: rgb(44,62,80);\n"
"    background:rgba(0, 0, 0, 0);\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\'; \n"
"    border:none;\n"
"}")
        self.label_listen_friends_list.setObjectName("label_listen_friends_list")
        self.verticalLayout_5.addWidget(self.label_listen_friends_list)
        self.listWidget_listen_friends_list = QtWidgets.QListWidget(parent=self.verticalFrame_2)
        self.listWidget_listen_friends_list.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.listWidget_listen_friends_list.setFont(font)
        self.listWidget_listen_friends_list.setStyleSheet("QListWidget {\n"
"    background: #ffffff;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    color: #2d3748;\n"
"    font-size: 15px;\n"
"    padding: 12px;\n"
"    margin: 4px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    min-height: 32px;\n"
"    padding: 2px 12px;\n"
"    border-radius: 6px;\n"
"    margin: 2px 0;\n"
"    transition: background 0.25s ease;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: #f8f9fa;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(44, 62, 80, 0.7);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    background: rgba(32, 45, 58, 0.7);\n"
"}\n"
"\n"
"QListWidget::item:!selected:hover {\n"
"    background: #f1f5f9;\n"
"}")
        self.listWidget_listen_friends_list.setObjectName("listWidget_listen_friends_list")
        self.verticalLayout_5.addWidget(self.listWidget_listen_friends_list)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_addItem_friend = QtWidgets.QToolButton(parent=self.verticalFrame_2)
        self.toolButton_addItem_friend.setStyleSheet("QToolButton {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255,255,255,0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(44,62,80,0.1);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgba(64,84,104,0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(44,62,80,0.15);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgba(34,52,70,0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(44,62,80,0.2);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    background-color: rgba(44,62,80,0.3);\n"
"    color: rgba(255,255,255,0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QToolButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(44,62,80,0.3),\n"
"                inset 0 0 0 1px rgba(255,255,255,0.2);\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.toolButton_addItem_friend.setObjectName("toolButton_addItem_friend")
        self.horizontalLayout_6.addWidget(self.toolButton_addItem_friend)
        self.toolButton_delItem_friend = QtWidgets.QToolButton(parent=self.verticalFrame_2)
        self.toolButton_delItem_friend.setStyleSheet("QToolButton {\n"
"    background-color: rgba(139, 0, 0, 0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255, 255, 255, 0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(139, 0, 0, 0.1);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgba(165, 42, 42, 0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(139, 0, 0, 0.15);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgba(128, 0, 0, 0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(139, 0, 0, 0.2);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    background-color: rgba(139, 0, 0, 0.3);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QToolButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(139, 0, 0, 0.3),\n"
"                inset 0 0 0 1px rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.toolButton_delItem_friend.setObjectName("toolButton_delItem_friend")
        self.horizontalLayout_6.addWidget(self.toolButton_delItem_friend)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addWidget(self.verticalFrame_2)
        self.verticalFrame_3 = QtWidgets.QFrame(parent=self.horizontalFrame)
        self.verticalFrame_3.setStyleSheet("QFrame {\n"
"    background-color: rgba(248, 249, 250, 0.8);\n"
"    border: 1px solid rgba(44, 62, 80, 0.12);\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 8px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    border-color: rgba(44, 62, 80, 0.2);\n"
"    box-shadow: 0 4px 16px rgba(44, 62, 80, 0.1);\n"
"    transform: translateY(-1px);\n"
"}\n"
"\n"
"QFrame:focus {\n"
"    border: 1px solid rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.1),\n"
"                0 6px 20px rgba(44, 62, 80, 0.15);\n"
"}\n"
"\n"
"QFrame::drop-shadow {\n"
"    background-color: rgba(44, 62, 80, 0.06);\n"
"    border-radius: 10px;\n"
"}")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_12 = QtWidgets.QLabel(parent=self.verticalFrame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_20.addWidget(self.label_12)
        self.checkBox_Global_listen = QtWidgets.QCheckBox(parent=self.verticalFrame_3)
        self.checkBox_Global_listen.setMinimumSize(QtCore.QSize(46, 26))
        self.checkBox_Global_listen.setMaximumSize(QtCore.QSize(46, 26))
        self.checkBox_Global_listen.setStyleSheet("QCheckBox {\n"
"    width: 16px;\n"
"    height: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 12px;\n"
"    padding: 0;\n"
"    border: 1px solid #8a8a8a;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.3);\n"
"    position: absolute;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QCheckBox:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: rgba(44,62,80,0.9);\n"
"    left: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;\n"
"    left: 21px;\n"
"}")
        self.checkBox_Global_listen.setText("")
        self.checkBox_Global_listen.setObjectName("checkBox_Global_listen")
        self.horizontalLayout_20.addWidget(self.checkBox_Global_listen)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtWidgets.QLabel(parent=self.verticalFrame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.checkBox_listen_room = QtWidgets.QCheckBox(parent=self.verticalFrame_3)
        self.checkBox_listen_room.setMinimumSize(QtCore.QSize(46, 26))
        self.checkBox_listen_room.setMaximumSize(QtCore.QSize(46, 26))
        self.checkBox_listen_room.setStyleSheet("QCheckBox {\n"
"    width: 16px;\n"
"    height: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 12px;\n"
"    padding: 0;\n"
"    border: 1px solid #8a8a8a;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.3);\n"
"    position: absolute;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QCheckBox:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: rgba(44,62,80,0.9);\n"
"    left: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;\n"
"    left: 21px;\n"
"}")
        self.checkBox_listen_room.setText("")
        self.checkBox_listen_room.setObjectName("checkBox_listen_room")
        self.horizontalLayout_18.addWidget(self.checkBox_listen_room)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_9 = QtWidgets.QLabel(parent=self.verticalFrame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_17.addWidget(self.label_9)
        self.checkBox_only_at = QtWidgets.QCheckBox(parent=self.verticalFrame_3)
        self.checkBox_only_at.setMinimumSize(QtCore.QSize(46, 26))
        self.checkBox_only_at.setMaximumSize(QtCore.QSize(46, 26))
        self.checkBox_only_at.setStyleSheet("QCheckBox {\n"
"    width: 16px;\n"
"    height: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 12px;\n"
"    padding: 0;\n"
"    border: 1px solid #8a8a8a;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.3);\n"
"    position: absolute;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QCheckBox:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: rgba(44,62,80,0.9);\n"
"    left: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;\n"
"    left: 21px;\n"
"}")
        self.checkBox_only_at.setText("")
        self.checkBox_only_at.setObjectName("checkBox_only_at")
        self.horizontalLayout_17.addWidget(self.checkBox_only_at)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_14 = QtWidgets.QLabel(parent=self.verticalFrame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_23.addWidget(self.label_14)
        self.checkBox_consent_Apply = QtWidgets.QCheckBox(parent=self.verticalFrame_3)
        self.checkBox_consent_Apply.setMinimumSize(QtCore.QSize(46, 26))
        self.checkBox_consent_Apply.setMaximumSize(QtCore.QSize(46, 26))
        self.checkBox_consent_Apply.setStyleSheet("QCheckBox {\n"
"    width: 16px;\n"
"    height: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 12px;\n"
"    padding: 0;\n"
"    border: 1px solid #8a8a8a;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.3);\n"
"    position: absolute;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QCheckBox:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: rgba(44,62,80,0.9);\n"
"    left: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;\n"
"    left: 21px;\n"
"}")
        self.checkBox_consent_Apply.setText("")
        self.checkBox_consent_Apply.setObjectName("checkBox_consent_Apply")
        self.horizontalLayout_23.addWidget(self.checkBox_consent_Apply)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_8 = QtWidgets.QLabel(parent=self.verticalFrame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_16.addWidget(self.label_8)
        self.checkBox_send_welcome = QtWidgets.QCheckBox(parent=self.verticalFrame_3)
        self.checkBox_send_welcome.setMinimumSize(QtCore.QSize(46, 26))
        self.checkBox_send_welcome.setMaximumSize(QtCore.QSize(46, 26))
        self.checkBox_send_welcome.setStyleSheet("QCheckBox {\n"
"    width: 16px;\n"
"    height: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 12px;\n"
"    padding: 0;\n"
"    border: 1px solid #8a8a8a;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.3);\n"
"    position: absolute;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QCheckBox:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: rgba(44,62,80,0.9);\n"
"    left: 1px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;\n"
"    left: 21px;\n"
"}")
        self.checkBox_send_welcome.setText("")
        self.checkBox_send_welcome.setObjectName("checkBox_send_welcome")
        self.horizontalLayout_16.addWidget(self.checkBox_send_welcome)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_5.addWidget(self.verticalFrame_3)
        self.verticalFrame_4 = QtWidgets.QFrame(parent=self.horizontalFrame)
        self.verticalFrame_4.setStyleSheet("QFrame {\n"
"    background-color: rgba(248, 249, 250, 0.8);\n"
"    border: 1px solid rgba(44, 62, 80, 0.12);\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 8px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    border-color: rgba(44, 62, 80, 0.2);\n"
"    box-shadow: 0 4px 16px rgba(44, 62, 80, 0.1);\n"
"    transform: translateY(-1px);\n"
"}\n"
"\n"
"QFrame:focus {\n"
"    border: 1px solid rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.1),\n"
"                0 6px 20px rgba(44, 62, 80, 0.15);\n"
"}\n"
"\n"
"QFrame::drop-shadow {\n"
"    background-color: rgba(44, 62, 80, 0.06);\n"
"    border-radius: 10px;\n"
"}")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_room_list = QtWidgets.QLabel(parent=self.verticalFrame_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_room_list.setFont(font)
        self.label_room_list.setStyleSheet("QLabel { \n"
"    color: rgb(44,62,80);\n"
"    background:rgba(0, 0, 0, 0);\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\'; \n"
"    border:none;\n"
"}")
        self.label_room_list.setObjectName("label_room_list")
        self.verticalLayout_8.addWidget(self.label_room_list)
        self.listWidget_listen_room_list = QtWidgets.QListWidget(parent=self.verticalFrame_4)
        self.listWidget_listen_room_list.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.listWidget_listen_room_list.setFont(font)
        self.listWidget_listen_room_list.setStyleSheet("QListWidget {\n"
"    background: #ffffff;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    color: #2d3748;\n"
"    font-size: 15px;\n"
"    padding: 12px;\n"
"    margin: 4px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    min-height: 32px;\n"
"    padding: 2px 12px;\n"
"    border-radius: 6px;\n"
"    margin: 2px 0;\n"
"    transition: background 0.25s ease;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: #f8f9fa;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(44, 62, 80, 0.7);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    background: rgba(32, 45, 58, 0.7);\n"
"}\n"
"\n"
"QListWidget::item:!selected:hover {\n"
"    background: #f1f5f9;\n"
"}")
        self.listWidget_listen_room_list.setObjectName("listWidget_listen_room_list")
        self.verticalLayout_8.addWidget(self.listWidget_listen_room_list)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.toolButton_addItem_room = QtWidgets.QToolButton(parent=self.verticalFrame_4)
        self.toolButton_addItem_room.setStyleSheet("QToolButton {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255,255,255,0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(44,62,80,0.1);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgba(64,84,104,0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(44,62,80,0.15);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgba(34,52,70,0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(44,62,80,0.2);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    background-color: rgba(44,62,80,0.3);\n"
"    color: rgba(255,255,255,0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QToolButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(44,62,80,0.3),\n"
"                inset 0 0 0 1px rgba(255,255,255,0.2);\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.toolButton_addItem_room.setObjectName("toolButton_addItem_room")
        self.horizontalLayout_14.addWidget(self.toolButton_addItem_room)
        self.toolButton_delItem_room = QtWidgets.QToolButton(parent=self.verticalFrame_4)
        self.toolButton_delItem_room.setStyleSheet("QToolButton {\n"
"    background-color: rgba(139, 0, 0, 0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255, 255, 255, 0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(139, 0, 0, 0.1);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgba(165, 42, 42, 0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(139, 0, 0, 0.15);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgba(128, 0, 0, 0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(139, 0, 0, 0.2);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    background-color: rgba(139, 0, 0, 0.3);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QToolButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(139, 0, 0, 0.3),\n"
"                inset 0 0 0 1px rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.toolButton_delItem_room.setObjectName("toolButton_delItem_room")
        self.horizontalLayout_14.addWidget(self.toolButton_delItem_room)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5.addWidget(self.verticalFrame_4)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_11.addWidget(self.horizontalFrame)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.lineEdit_room_admin = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lineEdit_room_admin.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_room_admin.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(248, 249, 250, 0.9);\n"
"    border: 1px solid rgba(44, 62, 80, 0.15);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    color: rgba(44, 62, 80, 0.9);\n"
"    selection-background-color: rgba(44, 62, 80, 0.3);\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 2px 6px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(44, 62, 80);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.15);\n"
"    background-color: rgba(255, 255, 255, 0.95);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: rgba(248, 249, 250, 0.5);\n"
"    color: rgba(44, 62, 80, 0.4);\n"
"    border-color: rgba(44, 62, 80, 0.08);\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(44, 62, 80, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: rgba(158, 42, 43, 0.6);\n"
"    box-shadow: 0 0 0 2px rgba(158, 42, 43, 0.1);\n"
"}")
        self.lineEdit_room_admin.setObjectName("lineEdit_room_admin")
        self.horizontalLayout_13.addWidget(self.lineEdit_room_admin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_21.addWidget(self.label_5)
        self.lineEdit_BaseURL = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lineEdit_BaseURL.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_BaseURL.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(248, 249, 250, 0.9);\n"
"    border: 1px solid rgba(44, 62, 80, 0.15);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    color: rgba(44, 62, 80, 0.9);\n"
"    selection-background-color: rgba(44, 62, 80, 0.3);\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 2px 6px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(44, 62, 80);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.15);\n"
"    background-color: rgba(255, 255, 255, 0.95);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: rgba(248, 249, 250, 0.5);\n"
"    color: rgba(44, 62, 80, 0.4);\n"
"    border-color: rgba(44, 62, 80, 0.08);\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(44, 62, 80, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: rgba(158, 42, 43, 0.6);\n"
"    box-shadow: 0 0 0 2px rgba(158, 42, 43, 0.1);\n"
"}")
        self.lineEdit_BaseURL.setObjectName("lineEdit_BaseURL")
        self.horizontalLayout_21.addWidget(self.lineEdit_BaseURL)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_11 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_22.addWidget(self.label_11)
        self.lineEdit_Prompt = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lineEdit_Prompt.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Prompt.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(248, 249, 250, 0.9);\n"
"    border: 1px solid rgba(44, 62, 80, 0.15);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    color: rgba(44, 62, 80, 0.9);\n"
"    selection-background-color: rgba(44, 62, 80, 0.3);\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 2px 6px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(44, 62, 80);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.15);\n"
"    background-color: rgba(255, 255, 255, 0.95);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: rgba(248, 249, 250, 0.5);\n"
"    color: rgba(44, 62, 80, 0.4);\n"
"    border-color: rgba(44, 62, 80, 0.08);\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(44, 62, 80, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: rgba(158, 42, 43, 0.6);\n"
"    box-shadow: 0 0 0 2px rgba(158, 42, 43, 0.1);\n"
"}")
        self.lineEdit_Prompt.setObjectName("lineEdit_Prompt")
        self.horizontalLayout_22.addWidget(self.lineEdit_Prompt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_19.addWidget(self.label_7)
        self.lineEdit_Model_1 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lineEdit_Model_1.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Model_1.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(248, 249, 250, 0.9);\n"
"    border: 1px solid rgba(44, 62, 80, 0.15);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    color: rgba(44, 62, 80, 0.9);\n"
"    selection-background-color: rgba(44, 62, 80, 0.3);\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 2px 6px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(44, 62, 80);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.15);\n"
"    background-color: rgba(255, 255, 255, 0.95);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: rgba(248, 249, 250, 0.5);\n"
"    color: rgba(44, 62, 80, 0.4);\n"
"    border-color: rgba(44, 62, 80, 0.08);\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(44, 62, 80, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: rgba(158, 42, 43, 0.6);\n"
"    box-shadow: 0 0 0 2px rgba(158, 42, 43, 0.1);\n"
"}")
        self.lineEdit_Model_1.setObjectName("lineEdit_Model_1")
        self.horizontalLayout_19.addWidget(self.lineEdit_Model_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.lineEdit_api_Token = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lineEdit_api_Token.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_api_Token.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(248, 249, 250, 0.9);\n"
"    border: 1px solid rgba(44, 62, 80, 0.15);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    color: rgba(44, 62, 80, 0.9);\n"
"    selection-background-color: rgba(44, 62, 80, 0.3);\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 2px 6px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(44, 62, 80);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.15);\n"
"    background-color: rgba(255, 255, 255, 0.95);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: rgba(248, 249, 250, 0.5);\n"
"    color: rgba(44, 62, 80, 0.4);\n"
"    border-color: rgba(44, 62, 80, 0.08);\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(44, 62, 80, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: rgba(158, 42, 43, 0.6);\n"
"    box-shadow: 0 0 0 2px rgba(158, 42, 43, 0.1);\n"
"}")
        self.lineEdit_api_Token.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_api_Token.setObjectName("lineEdit_api_Token")
        self.horizontalLayout_15.addWidget(self.lineEdit_api_Token)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_25.setSpacing(12)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_17 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_25.addWidget(self.label_17)
        self.listWidget_greet = QtWidgets.QListWidget(parent=self.scrollAreaWidgetContents)
        self.listWidget_greet.setMinimumSize(QtCore.QSize(0, 88))
        self.listWidget_greet.setStyleSheet("QListWidget {\n"
"    background: #ffffff;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    color: #2d3748;\n"
"    font-size: 15px;\n"
"    padding: 4px;\n"
"    margin: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    min-height: 32px;\n"
"    padding: 2px 12px;\n"
"    border-radius: 6px;\n"
"    margin: 2px 0;\n"
"    transition: background 0.25s ease;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: #f8f9fa;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(44, 62, 80, 0.7);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    background: rgba(32, 45, 58, 0.7);\n"
"}\n"
"\n"
"QListWidget::item:!selected:hover {\n"
"    background: #f1f5f9;\n"
"}")
        self.listWidget_greet.setObjectName("listWidget_greet")
        self.horizontalLayout_25.addWidget(self.listWidget_greet)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_add_greet = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton_add_greet.setStyleSheet("QPushButton {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255,255,255,0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(44,62,80,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(64,84,104,0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(44,62,80,0.15);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(34,52,70,0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(44,62,80,0.2);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(44,62,80,0.3);\n"
"    color: rgba(255,255,255,0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(44,62,80,0.3),\n"
"                inset 0 0 0 1px rgba(255,255,255,0.2);\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QPushButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.pushButton_add_greet.setObjectName("pushButton_add_greet")
        self.verticalLayout_12.addWidget(self.pushButton_add_greet)
        self.pushButton_del_greet = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton_del_greet.setStyleSheet("QPushButton {\n"
"    background-color: rgba(139, 0, 0, 0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255, 255, 255, 0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(139, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(165, 42, 42, 0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(139, 0, 0, 0.15);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(128, 0, 0, 0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(139, 0, 0, 0.2);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(139, 0, 0, 0.3);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(139, 0, 0, 0.3),\n"
"                inset 0 0 0 1px rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QPushButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.pushButton_del_greet.setObjectName("pushButton_del_greet")
        self.verticalLayout_12.addWidget(self.pushButton_del_greet)
        self.horizontalLayout_25.addLayout(self.verticalLayout_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_15 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_24.addWidget(self.label_15)
        self.lineEdit_room_welcome = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lineEdit_room_welcome.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_room_welcome.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(248, 249, 250, 0.9);\n"
"    border: 1px solid rgba(44, 62, 80, 0.15);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    color: rgba(44, 62, 80, 0.9);\n"
"    selection-background-color: rgba(44, 62, 80, 0.3);\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: rgba(44, 62, 80, 0.3);\n"
"    box-shadow: 0 2px 6px rgba(44, 62, 80, 0.05);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(44, 62, 80);\n"
"    box-shadow: 0 0 0 2px rgba(44, 62, 80, 0.15);\n"
"    background-color: rgba(255, 255, 255, 0.95);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: rgba(248, 249, 250, 0.5);\n"
"    color: rgba(44, 62, 80, 0.4);\n"
"    border-color: rgba(44, 62, 80, 0.08);\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(44, 62, 80, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: rgba(158, 42, 43, 0.6);\n"
"    box-shadow: 0 0 0 2px rgba(158, 42, 43, 0.1);\n"
"}")
        self.lineEdit_room_welcome.setObjectName("lineEdit_room_welcome")
        self.horizontalLayout_24.addWidget(self.lineEdit_room_welcome)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, 12, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.pushButton_load = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_load.setStyleSheet("QPushButton {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255,255,255,0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(44,62,80,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(64,84,104,0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(44,62,80,0.15);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(34,52,70,0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(44,62,80,0.2);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(44,62,80,0.3);\n"
"    color: rgba(255,255,255,0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(44,62,80,0.3),\n"
"                inset 0 0 0 1px rgba(255,255,255,0.2);\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QPushButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_8.addWidget(self.pushButton_load)
        self.pushButton_save = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    background-color: rgba(44,62,80,0.9);\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    color: rgba(255,255,255,0.95);\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    min-width: 40px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 2px 4px rgba(44,62,80,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(64,84,104,0.95);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 8px rgba(44,62,80,0.15);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(34,52,70,0.9);\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 1px 2px rgba(44,62,80,0.2);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(44,62,80,0.3);\n"
"    color: rgba(255,255,255,0.5);\n"
"    box-shadow: none;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 2px rgba(44,62,80,0.3),\n"
"                inset 0 0 0 1px rgba(255,255,255,0.2);\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QPushButton::menu-button {\n"
"    width: 0;\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_8.addWidget(self.pushButton_save)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.MainFrame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.listWidget_Head.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)
        self.listWidget_Head.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Head_Titlelabel.setText(_translate("MainWindow", "Siver 智能机器人"))
        __sortingEnabled = self.listWidget_Head.isSortingEnabled()
        self.listWidget_Head.setSortingEnabled(False)
        item = self.listWidget_Head.item(0)
        item.setText(_translate("MainWindow", "欢迎"))
        item = self.listWidget_Head.item(1)
        item.setText(_translate("MainWindow", "自动化"))
        item = self.listWidget_Head.item(2)
        item.setText(_translate("MainWindow", "关于"))
        self.listWidget_Head.setSortingEnabled(__sortingEnabled)
        self.label_Title.setText(_translate("MainWindow", "<html><head/><body><p>Siver Bot <span style=\" font-size:12pt; color:#989898;\">V1.0</span></p></body></html>"))
        self.label_welcome.setText(_translate("MainWindow", "欢迎回来，"))
        self.label_Nickname.setText(_translate("MainWindow", "Siver"))
        self.pushButton_start.setText(_translate("MainWindow", "开启"))
        self.label_time.setText(_translate("MainWindow", "000:00:00"))
        self.label_Online_Status.setText(_translate("MainWindow", "在线"))
        self.label_listen_friends_list.setText(_translate("MainWindow", "监听用户"))
        self.toolButton_addItem_friend.setText(_translate("MainWindow", "添加"))
        self.toolButton_delItem_friend.setText(_translate("MainWindow", "删除"))
        self.label_12.setText(_translate("MainWindow", "全局监听"))
        self.label_10.setText(_translate("MainWindow", "启用群监听"))
        self.label_9.setText(_translate("MainWindow", "群聊仅被@时回复"))
        self.label_14.setText(_translate("MainWindow", "自动同意好友申请"))
        self.label_8.setText(_translate("MainWindow", "群聊发送新人欢迎语"))
        self.label_room_list.setText(_translate("MainWindow", "监听群聊"))
        self.toolButton_addItem_room.setText(_translate("MainWindow", "添加"))
        self.toolButton_delItem_room.setText(_translate("MainWindow", "删除"))
        self.label_4.setText(_translate("MainWindow", "管理员（Admin）   ："))
        self.lineEdit_room_admin.setPlaceholderText(_translate("MainWindow", "输入群聊管理员的备注，管理员可以操控智能体。"))
        self.label_5.setText(_translate("MainWindow", "模型网址（URL）   ："))
        self.lineEdit_BaseURL.setPlaceholderText(_translate("MainWindow", "输入您的大模型网络地址（URL）。"))
        self.label_11.setText(_translate("MainWindow", "提示词（prompt） ："))
        self.lineEdit_Prompt.setPlaceholderText(_translate("MainWindow", "输入模型提示词。"))
        self.label_7.setText(_translate("MainWindow", "首选模型（Model）："))
        self.lineEdit_Model_1.setPlaceholderText(_translate("MainWindow", "在此输入模型的名字。"))
        self.label_6.setText(_translate("MainWindow", "模型令牌（Token） ："))
        self.lineEdit_api_Token.setPlaceholderText(_translate("MainWindow", "或者输入API Key。"))
        self.label_17.setText(_translate("MainWindow", "新好友打招呼消息  ："))
        self.pushButton_add_greet.setText(_translate("MainWindow", "添加"))
        self.pushButton_del_greet.setText(_translate("MainWindow", "删除"))
        self.label_15.setText(_translate("MainWindow", "群聊新人欢迎信息："))
        self.lineEdit_room_welcome.setPlaceholderText(_translate("MainWindow", "欢迎新成员！"))
        self.pushButton_load.setText(_translate("MainWindow", "加载配置"))
        self.pushButton_save.setText(_translate("MainWindow", "保存配置"))
